apiVersion: v1
kind: Service
metadata:
  name: tbbpython-service
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
    nodePort: 30110
  selector:
    app: tbbpython

