apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  namespace: dev
  labels:
    app: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_INSTANCE_NAME
          value: sehirler
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv-dev
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv-dev
        persistentVolumeClaim:
          claimName: mysql-pvc-dev

