apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dev
  namespace: dev
spec:
  storageClassName: manual-dev
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
