apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-prod
  namespace: prod
spec:
  storageClassName: manual-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
