apiVersion: v1
kind: Service
metadata:
  name: mydb
  namespace: prod
  labels:
    app: mydb
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mydb
    nodePort: 30700
  selector:
    app: mydb
  type: NodePort
